version: "3.9"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Moscow
      - INIT_SESSION=MinerSession
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8192M
